// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI(db push, migrate) 실행 시에는 directUrl(5432 포트)을 사용하고,
    // 없는 경우 DATABASE_URL을 바라보도록 설정합니다.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
